--liquibase formatted sql

--changeset youyu.dong:1510225200570-1
ALTER TABLE TD_METRIC_DAY  modify  `active_new_users`  int(11) DEFAULT 0 COMMENT '进店新客';
ALTER TABLE TD_METRIC_DAY  modify  `active_old_users`  int(11) DEFAULT 0 COMMENT '进店老客';
ALTER TABLE TD_METRIC_DAY  modify  `active_users`  int(11) DEFAULT 0 COMMENT '进店人数';
ALTER TABLE TD_METRIC_DAY  modify  `stay_new_users`  int(11) DEFAULT 0 COMMENT '停留新客';
ALTER TABLE TD_METRIC_DAY  modify  `stay_old_users`  int(11) DEFAULT 0 COMMENT '停留老客';
ALTER TABLE TD_METRIC_DAY  modify  `stay_users`  int(11) DEFAULT 0 COMMENT '停留人数';
ALTER TABLE TD_METRIC_DAY  modify  `front_users`  int(11) DEFAULT 0 COMMENT '周边人数';
ALTER TABLE TD_METRIC_DAY  modify  `jump_users`  int(11) DEFAULT 0 COMMENT '跳出人数';
ALTER TABLE TD_METRIC_DAY  modify  `high_active_users`  int(11) DEFAULT 0 COMMENT '高活跃人数';
ALTER TABLE TD_METRIC_DAY  modify  `middle_active_users`  int(11) DEFAULT 0 COMMENT '中活跃人数';
ALTER TABLE TD_METRIC_DAY  modify  `low_active_users`  int(11) DEFAULT 0 COMMENT '低活跃人数';
ALTER TABLE TD_METRIC_DAY  modify  `sleep_active_users`  int(11) DEFAULT 0 COMMENT '沉睡人数';
ALTER TABLE TD_METRIC_DAY  modify  `high_stay_users`  int(11) DEFAULT 0 COMMENT '高活跃停留人数';
ALTER TABLE TD_METRIC_DAY  modify  `middle_stay_users`  int(11) DEFAULT 0 COMMENT '中活跃停留人数';
ALTER TABLE TD_METRIC_DAY  modify  `low_stay_users`  int(11) DEFAULT 0 COMMENT '低活跃停留人数';
ALTER TABLE TD_METRIC_DAY  modify  `sleep_stay_users`  int(11) DEFAULT 0 COMMENT '沉睡停留人数';
ALTER TABLE TD_METRIC_DAY  modify  `recent7Users`  int(11) DEFAULT 0 COMMENT '近7日入店客流';
ALTER TABLE TD_METRIC_DAY  modify  `recent30HighRate`  int(11) DEFAULT 0 COMMENT '近30日高活跃客群占比';
ALTER TABLE TD_METRIC_DAY  modify  `active_duration`  int(11) DEFAULT 0 COMMENT '到访总时长';
ALTER TABLE TD_METRIC_DAY  modify  `active_times`  int(11) DEFAULT 0 COMMENT '到访总次数';
ALTER TABLE TD_METRIC_DAY  modify  `stay_duration`  int(11) DEFAULT 0 COMMENT '停留总时长';
ALTER TABLE TD_METRIC_DAY  modify  `stay_times`  int(11) DEFAULT 0 COMMENT '停留总次数';
ALTER TABLE TD_METRIC_DAY  modify  `interval_2`  int(11) DEFAULT 0 COMMENT '2两分钟区间次数';
ALTER TABLE TD_METRIC_DAY  modify  `interval_5`  int(11) DEFAULT 0 COMMENT '2到5分钟区间次数';
ALTER TABLE TD_METRIC_DAY  modify  `interval_10`  int(11) DEFAULT 0 COMMENT '5-10分钟区间次数';
ALTER TABLE TD_METRIC_DAY  modify  `interval_15`  int(11) DEFAULT 0 COMMENT '10-15分钟区间次数';
ALTER TABLE TD_METRIC_DAY  modify  `visit_cycle`  int(11) DEFAULT 0 COMMENT '到访周期';
ALTER TABLE TD_METRIC_DAY  modify  `sales_amount`  int(11) DEFAULT 0 COMMENT '销售金额';
ALTER TABLE TD_METRIC_DAY  modify  `order_count`  int(11) DEFAULT 0 COMMENT '订单数';
ALTER TABLE TD_METRIC_DAY  modify  `order_average_price`  int(11) DEFAULT 0 COMMENT '订单均价';
ALTER TABLE TD_METRIC_DAY  modify  `receipt_count`  int(11) DEFAULT 0 COMMENT'转化数,小票数';
ALTER TABLE TD_METRIC_DAY  modify  `member_count`  int(11) DEFAULT 0 COMMENT'会员数';
ALTER TABLE TD_METRIC_DAY  modify  `potential_count`  int(11) DEFAULT 0 COMMENT'潜客数';
ALTER TABLE TD_METRIC_DAY  modify  `singular_price`  int(11) DEFAULT 0 COMMENT'件单价';
ALTER TABLE TD_METRIC_DAY  modify  `customer_price`  int(11) DEFAULT 0 COMMENT'客单价';
ALTER TABLE TD_METRIC_DAY  modify  `rpc`  int(11) DEFAULT 0 COMMENT'rpc';
ALTER TABLE TD_METRIC_DAY  modify  `vpc`  int(11) DEFAULT 0 COMMENT'vpc';
ALTER TABLE TD_METRIC_DAY  modify  `member_single_price`  int(11) DEFAULT 0 COMMENT'会员成交单价';
ALTER TABLE TD_METRIC_DAY  modify  `non_member_single_price`  int(11) DEFAULT 0 COMMENT'非会员成交单价';
ALTER TABLE TD_METRIC_DAY  modify  `average_order_nums`  int(11) DEFAULT 0 COMMENT'平均订单件数';
ALTER TABLE TD_METRIC_DAY  modify  `new_active_duration`  int(11) DEFAULT 0 COMMENT'新客到访时长';
ALTER TABLE TD_METRIC_DAY  modify  `new_active_time`  int(11) DEFAULT 0 COMMENT'新客到访次数';
ALTER TABLE TD_METRIC_DAY  modify  `old_active_duration`  int(11) DEFAULT 0 COMMENT'老客到访时长';
ALTER TABLE TD_METRIC_DAY  modify  `old_active_time`  int(11) DEFAULT 0 COMMENT'老客到访次数';
ALTER TABLE TD_METRIC_DAY  modify  `member_order_average_price`  int(11) DEFAULT 0 COMMENT'会员订单均价';
ALTER TABLE TD_METRIC_DAY  modify  `non_member_order_average_price`  int(11) DEFAULT 0 COMMENT'非会员订单均价';
ALTER TABLE TD_METRIC_DAY  modify  `relation_order_rate`  varchar(10) DEFAULT '0' COMMENT'关联销售订单占比';
ALTER TABLE TD_METRIC_DAY  modify  `member_relation_order_rate`  varchar(10) DEFAULT '0' COMMENT'会员关联销售订单占比';
ALTER TABLE TD_METRIC_DAY  modify  `non_member_relation_order_rate`  varchar(10) DEFAULT '0' COMMENT'非会员关联销售订单占比';
