export const EventType = {
    'DATACHANGE':'DATACHANGE',
    'STYLECHANGE':'STYLECHANGE',
    'SIZECHANGE':'SIZECHANGE',
    'VISUALAREA':'VISUALAREA',
    'CONFCHANGE':'CONFCHANGE',
    'VISUALAREAINIT':'VISUALAREAINIT',
    'REFRESHSTAGE':'REFRESHSTAGE',
    'CHARTUPDATE':'CHARTUPDATE',
    'GROUPUPDATE':'GROUPUPDATE'
};

export const ComponentEvent = {
    "COMSELECT":"COMSELECT",
    "COMRIGHTMENU":"COMRIGHTMENU",
    "DRAGSELEECT":"DRAGSELEECT",
    "STAGECLICK":"STAGECLICK",
    'FILTERCHANGE':'FILTERCHANGE',
    'COMFILTERCHANGE':'COMFILTERCHANGE',
    'CHARTFILTERCHANGE':'CHARTFILTERCHANGE',
    'TOGGLECOMPONENT':'TOGGLECOMPONENT',
    "COMRESIZE":"COMRESIZE"
}

export const AlignType = {
    "ACTION":"ACTION",
    "LEFT":"LEFT",
    "RIGHT":"RIGHT",
    "TOP":"TOP",
    "BOTTOM":"BOTTOM",
    "VERTICAL_CENTER":"VERTICAL_CENTER",
    "HORIZ_CENTER":"HORIZ_CENTER"
}

