--liquibase formatted sql

--changeset junmin.li:1497354897007-1
drop table offline_active_frequency_distribution_counter;
drop table offline_active_user_room_day_counter;
drop table offline_active_user_room_times_day_counter;
drop table offline_enter_new_user_day_counter;
drop table offline_enter_old_user_day_counter;
drop table offline_enter_times_distribution_counter;
drop table offline_enter_user_day_counter;
drop table offline_enter_user_room_day_counter;
drop table offline_enter_user_room_times_day_counter;
drop table offline_enter_user_times_day_counter;
drop table offline_project_user_times_counter;
drop table offline_stay_user_room_day_counter;
drop table offline_stay_user_room_duration_day_counter;
drop table offline_stay_user_room_times_day_counter;
drop table offline_stay_user_room_tracks_counter;



