# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  profiles:
    active: saas

  datasource:
    name: wifianalytics_merge
    url: jdbc:mysql://172.23.5.110:3306/wifianalytics_merge?characterEncoding=utf-8&&zeroDateTimeBehavior=convertToNull&&autoReconnect=true
    username: wifianalytics
    password: wifianalytics
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    expire: 3600
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  sentinel:
    host: 172.23.5.111:26379
    master: mymaster

server:
    port: 8080

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# =======================Wreport Properties==========================

app:
  service:
    security:
    home:
cas:
  service:
    login:
    logout:
  url:
    prefix:

td-aacount-url: https://debug.talkingdata.com/debugAccount
#JOB
systemcode: wreport
#--------

appcode: wreport
apptaken: e10adc3949ba59abbe56e057f20f883e
menu: MENU
button: BUTTON
manifest-build-version: 1.0.0
azkabanUrl: ""
azkabanUserName: ""
azkabanPassword: ""
passengerDistributionMaxSensor: 50
dmp-console-url: http://172.23.5.114:8899/config/admin
upload:
  path:  /nfs

apigateway-mcUrl: http://router.apigateway.talkingdata.com/sbsmc
apigateway-appKey: 82461359
apigateway-appSecret: 7ad584d0a22a42f9b1eca8e718b1ecd3
apigateway-appSignature: 0840fa7116945e9ecc08d6df5354fd0a
apigateway-tid: TGae14bdaa428744f59714fab0cd06916f
apigateway-tkey: 57f0764da4e14c96bdc5f4118e0bd47b