--liquibase formatted sql

--changeset junmin.li:1487162749672-1
INSERT INTO `wifianalytics_meta`.`TD_METRIC` (`id`, `cube_id`, `name`, `type`, `column_id`, `compute_by`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('80', '81', 'offline_project_enter_duration_distribute_counter', '1', '403', 'counter', NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
INSERT INTO `wifianalytics_meta`.`TD_FACT_TABLE` (`id`, `name`, `version`, `domain_id`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('80', 'offline_project_enter_duration_distribute_counter', '1', '2', NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:41', '2017-02-15 20:58:41');
INSERT INTO `wifianalytics_meta`.`TD_DIMENSION` (`id`, `cube_id`, `name`, `default_value`, `display_name`, `column_id`, `type`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('346', '81', 'tenant_id', 'tenant_id', NULL, '399', '0', NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:41', '2017-02-15 20:58:41');
INSERT INTO `wifianalytics_meta`.`TD_DIMENSION` (`id`, `cube_id`, `name`, `default_value`, `display_name`, `column_id`, `type`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('347', '81', 'project_id', 'project_id', NULL, '400', '0', NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
INSERT INTO `wifianalytics_meta`.`TD_DIMENSION` (`id`, `cube_id`, `name`, `default_value`, `display_name`, `column_id`, `type`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('348', '81', 'date', 'date', NULL, '401', '0', NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
INSERT INTO `wifianalytics_meta`.`TD_DIMENSION` (`id`, `cube_id`, `name`, `default_value`, `display_name`, `column_id`, `type`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('349', '81', 'duration', 'duration', NULL, '402', '0', NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
INSERT INTO `wifianalytics_meta`.`TD_CUBE` (`id`, `name`, `owner`, `description`, `fact_table_id`, `domain_id`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('81', 'offline_project_enter_duration_distribute_counter', NULL, 'offline_project_enter_duration_distribute_counter', '80', '2', NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:41', '2017-02-15 20:58:41');
INSERT INTO `wifianalytics_meta`.`TD_COLUMN` (`id`, `name`, `type`, `fact_id`, `not_null`, `length`, `another_name`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('399', 'tenant_id', 'varchar', '80', 0, '64', NULL, NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:41', '2017-02-15 20:58:41');
INSERT INTO `wifianalytics_meta`.`TD_COLUMN` (`id`, `name`, `type`, `fact_id`, `not_null`, `length`, `another_name`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('400', 'project_id', 'int', '80', 0, '10', NULL, NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
INSERT INTO `wifianalytics_meta`.`TD_COLUMN` (`id`, `name`, `type`, `fact_id`, `not_null`, `length`, `another_name`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('401', 'date', 'varchar', '80', 0, '10', NULL, NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
INSERT INTO `wifianalytics_meta`.`TD_COLUMN` (`id`, `name`, `type`, `fact_id`, `not_null`, `length`, `another_name`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('402', 'duration', 'varchar', '80', 0, '10', NULL, NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
INSERT INTO `wifianalytics_meta`.`TD_COLUMN` (`id`, `name`, `type`, `fact_id`, `not_null`, `length`, `another_name`, `data_app_id`, `tenant_id`, `creator`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES ('403', 'offset', 'int', '80', 0, '10', NULL, NULL, NULL, 'tools', 'tools', 'tools', '2017-02-15 20:58:42', '2017-02-15 20:58:42');
