define(['angularAMD', 
        'angular',
        'angular-locale_zh', 
        'angular-ui-bootstrap', 
        'angular-ui-router',
		'angular-strap', 
		'angular-strap-tpl',
		'restangular',
		'angular-ui-tree',
		'ng-table',
		'app/controllers/common/AccordionMenuController',
		'util','week','month','day_week_month','calendar_base','calendar',
		'customUtilJS',
		'color-picker',
		'isteven-multi-select',
		'ng-file-upload-shim',
		'ng-file-upload',
		'app/service/ConditionService',
		'app/directive/TdPanel',
		'app/directive/TdDateCondition',
		'app/common/TableOptions',
		'app/common/FormartUtils',
		'app/common/CommonUtils',
		'app/directive/TdDateCondition',
		'app/directive/TdIndicators',
		'app/common/rgba',
		'jquery'], function(angularAMD) {
	'use strict';
	return angularAMD;
});