require.config({
  baseUrl: 'js/',  
  waitSeconds: 0,

  // alias libraries paths.  Must set 'angular'
  paths: {
	    'underscore': "/enterprise/js/libs/restangular/underscore.min",
	    'lodash': "/enterprise/js/libs/restangular/lodash.min",
	    'jquery': '/enterprise/js/libs/jquery/jquery-1.12.3.min',
	    'jquery-scroll': '/enterprise/js/libs/jquery-scroll/jquery-scroll',
	    'angular': '/enterprise/js/libs/angular/angular.min',
	    'angular-route': '/enterprise/js/libs/angular-route/angular-route.min',    
	    'angularAMD': '/enterprise/js/libs/angularAMD/angularAMD.min',
	    'angular-locale_zh' : '/enterprise/js/libs/angular-locale/angular-locale_zh.min',
	    'ngload': '/enterprise/js/libs/angularAMD/ngload.min',
	    'angular-ui-bootstrap': '/enterprise/js/libs/angular-ui/angular-bootstrap/ui-bootstrap-tpls.min',
	    'angular-ui-router': '/enterprise/js/libs/angular-ui/angular-ui-router/angular-ui-router.min',
	    'restangular': '/enterprise/js/libs/restangular/restangular.min',
	    'angular-animate': '/enterprise/js/libs/angular-animate/angular-animate.min',
	    'angular-strap': '/enterprise/js/libs/angular-strap/angular-strap.min',
	    'angular-strap-tpl': '/enterprise/js/libs/angular-strap/angular-strap.tpl.min',
	    'angular-ui-tree': '/enterprise/js/libs/angular-ui/angular-ui-tree/angular-ui-tree.min',
	    'customUtilJS': '/enterprise/js/customUtilJS',
	    'ng-table': "/enterprise/js/libs/ng-table/ng-table",
	    'table-freeze': 'libs/table-freeze/table-freeze',
	    'ng-file-upload-shim': "/enterprise/js/libs/ng-file-upload/ng-file-upload-shim.min",
	    'ng-file-upload': "/enterprise/js/libs/ng-file-upload/ng-file-upload.min",
	    'color-picker': 'libs/color-picker/color-picker',
	    
	    'util':'/enterprise/js/libs/calender/util',
	    'week':'/enterprise/js/libs/calender/week',
	    'month':'/enterprise/js/libs/calender/month',
	    'calendar_base':'/enterprise/js/libs/calender/calendar_base',
	    'calendar':"/enterprise/js/libs/calender/calendar.min",
	    'day_week_month':"/enterprise/js/libs/calender/day_week_month",
	    
	    'highchart': '/enterprise/js/libs/highcharts/highcharts.v4.2.5',
	    'highchart-more': '/enterprise/js/libs/highcharts/highcharts-more',
	    'exporting':"/enterprise/js/libs/highcharts/exporting",
	    'echarts': 'libs/echarts/echarts',
	    'china': 'libs/echarts/china',
	    'world': 'libs/echarts/world',
	    
	    'dark': 'libs/echarts/theme/dark',
	    'infographic': 'libs/echarts/theme/infographic',
	    'macarons': 'libs/echarts/theme/macarons',
	    'roma': 'libs/echarts/theme/roma',
	    'shine': 'libs/echarts/theme/shine',
	    'vintage': 'libs/echarts/theme/vintage',
	    
	    'ng-pagination': 'libs/ng-pagination/ng-pagination',
	    'isteven-multi-select': 'libs/isteven-multi-select/isteven-multi-select',
  },
  map: {
      '*': {
          'css': '/enterprise/js/libs/require-css/css.min.js'
      }
  }, 
  shim: {
	'angular' : {
		deps: [
		    'css!/enterprise/css/libs/bootstrap/bootstrap.min',
		    'css!/enterprise/css/libs/bootstrap-datepicker/bootstrap-datepicker',
		    'css!/enterprise/css/libs/angular-motion/angular-motion.min',
		    'css!/enterprise/css/libs/ng-table/ng-table',
		    'css!/enterprise/css/libs/ui-tree/angular-ui-tree',
		    'css!/enterprise/css/libs/angular-strap/angular-strap.min',
		    'css!/enterprise/css/libs/fast-date/fast-date',
		    'css!/enterprise/css/libs/zTreeStyle/zTreeStyle',
		    'css!/enterprise/css/app/common/main',
		    'css!/enterprise/css/app/ng-table/ng-table',
		    'css!/enterprise/css/app/searchTagator/searchTagator',
		    'css!/enterprise/css/app/calender/calender',
		    
		    'css!../css/main',
		    'css!../css/plugin',
		    'css!../css/common/calender',
		    'css!../css/common/common',
		    'css!../css/common/select',
		    'css!../css/common/table',
		    'css!../css/common/color-picker',
		    'css!../css/common/dialog.css',
		    'css!../css/app/directive',
		    'css!../css/app/securities',
		    'css!../css/app/visualization',
		    'css!../css/app/visualization-extend',
		    'css!../css/ng-pagination/ng-pagination.css',
		    
		    'css!libs/isteven-multi-select/isteven-multi-select.css',
		    'css!../css/app/td-isteven-multi-select.css',
		],
		exports: 'angular'
	},
    'angular-route': [ 'angular' ],
    'angularAMD': [ 'angular' ],
    'angular-locale_zh':['angular'],
    'ngload': [ 'angularAMD' ],
    'angular-ui-bootstrap': [ 'angular' ],
    'angular-ui-router': [ 'angular' ],
    'restangular': ['angular', 'underscore', 'lodash'],
    'angular-animate': ['angular'],
    'angular-strap': ['angular', 'angular-animate'],
    'angular-strap-tpl': ['angular-strap'],
    'angular-ui-tree' : ['angular'],
    'ng-file-upload-shim': [ 'angular' ],
    'ng-file-upload': [ 'angular' ],
    'table-freeze':['jquery'],
    'color-picker': [ 'angular' ],
    'ng-pagination': [ 'angular' ],
    'isteven-multi-select': [ 'angular' ],
    'ng-table': ['angular','table-freeze'],
    'highchart':['jquery'],
    'highchart-more':['jquery','highchart'],
    'exporting':['jquery','highchart','highchart-more'],
    'util':['jquery'],
    'week':['jquery','util'],
    'month':['jquery','util'],
    'day_week_month':['jquery','util'],
    'calendar_base':['jquery','util'],
    'calendar':['jquery','util'],
    'customUtilJS': [ 'jquery' ]
  },

  // kick start application
  deps: ['app']
});
