--liquibase formatted sql

--changeset yinglei.li:1507740231121-1
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'ftp.host', 'h3crd-wlan1.chinacloudapp.cn', 'FTP HOST主机，配置多套FTP以逗号分隔', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-10-12 00:41:41', '2017-10-12 00:41:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'ftp.port', '21', 'FTP端口，配置多套FTP以逗号分隔', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-10-12 00:41:41', '2017-10-12 00:41:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'ftp.username', 'bestseller', 'FTP用户名，配置多套FTP以逗号分隔', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-10-12 00:41:41', '2017-10-12 00:41:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'ftp.password', 'bestsellersecurity', 'FTP密码，配置多套FTP以逗号分隔', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-10-12 00:41:41', '2017-10-12 00:41:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'ftp.passiveMode', 'true', 'FTP被动模式，配置多套FTP以逗号分隔', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-10-12 00:41:41', '2017-10-12 00:41:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'ftp.encoding', 'UTF-8', 'FTP编码方式，配置多套FTP以逗号分隔', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-10-12 00:41:41', '2017-10-12 00:41:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'ftp.client.timeout', '10000', 'FTP客户端超时时间，单位毫秒ms，配置多套FTP以逗号分隔', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-10-12 00:41:41', '2017-10-12 00:41:41', '0');

