--liquibase formatted sql

--changeset yinglei.li:1506442258643-1
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'jump.user.visit.minutes', '2', '项目有效跳出客流阀值，单位是分钟，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'high.active.begin.user.days', '1', '距上次到访高活跃区间开始天数，单位是天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'high.active.end.user.days', '7', '距上次到访高活跃区间结束天数，单位是天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'medium.active.begin.user.days', '8', '距上次到访中活跃区间开始天数，单位是天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'medium.active.end.user.days', '30', '距上次到访中活跃区间结束天数，单位是天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'low.active.begin.user.days', '31', '距上次到访低活跃区间开始天数，单位是天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'low.active.end.user.days', '120', '距上次到访低活跃区间结束天数，单位是天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'sleep.user.days', '121', '距上次到访沉睡客流阀值，单位是天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'default.before.rssi', '-80', '项目探针信号强度店前客流，过滤规则>=-80,如果小于-80 则判定为店前客流', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'sales.consecutive.days', '30', '店员连续天数，单位为天，全局默认，店员阈值优先级高于黑名单阈值，即 某设备被判断为“店员”后，即使触发黑名单阈值，也不会被标记进入黑名单', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'sales.come.days', '30', '店员入店天数，单位为天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'sales.max.duration.hours', '240', '一天内入店停留时间累积，单位为天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'black.consecutive.days', '30', '黑名单连续天数，单位为天，全局默认，店员阈值优先级高于黑名单阈值，即 某设备被判断为“店员”后，即使触发黑名单阈值，也不会被标记进入黑名单', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');
INSERT INTO `TD_PARAM` (`id`, `param_key`, `param_value`, `description`, `system_code`, `create_by`, `creator`, `update_by`, `create_time`, `update_time`, `is_password`) VALUES (null, 'black.come.days', '30', '黑名单入店天数，单位为天，全局默认', 'wreport', 'WifiAnalytics', 'WifiAnalytics', NULL, '2017-09-26 23:51:41', '2017-09-26 23:51:41', '0');

